### Einen Vereine mittels PATCH aktualisieren
PATCH {{baseUrl}}/00000000-0000-0000-0000-000000000040
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

[
    { "op": "replace", "path": "/name", "value": "Neuernamepatch" },
    { "op": "replace", "path": "/email", "value": "new.email@test.depatch" },
    { "op": "add", "path": "/interessen", "value": "S" },
    { "op": "remove", "path": "/interessen", "value": "L" }
]

> {%
    client.test('Einen Vereine mittels PATCH aktualisieren: No Content (204)', () => {
        const status = response.status;
        client.assert(status === 204, `Falscher Statuscode: ${status}`);
    });

    client.test('Einen Vereine mittels PATCH aktualisieren: leerer body', () => {
        const body = response.body;
        client.assert(body === null, `body: ${JSON.stringify(body)}`);
    });
%}

### Einen Vereine mit fehlerhaften Daten mittels PATCH aktualisieren
PATCH {{baseUrl}}/00000000-0000-0000-0000-000000000040
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

[
    { "op": "replace", "path": "/name", "value": "?!" },
    { "op": "replace", "path": "/email", "value": "emailungueltig@" }
]

> {%
    client.test('Einen Vereine mittels PATCH und fehlerhaften Daten aktualisieren: Unprocessable Entity (422)', () => {
        const status = response.status;
        client.assert(status === 422, `Falscher Statuscode: ${status}`);
    });

    client.test('Einen Vereine mittels PATCH und fehlerhaften Daten aktualisieren: application/problem+json', () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === "application/problem+json", `Falscher MIME-Typ: ${mimeType}`);
    });

    client.test('Einen Vereine mittels PATCH und fehlerhaften Daten aktualisieren: body mit ProblemDetail', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
        const detail = body.detail;
        client.assert(detail !== null && detail !== undefined && typeof detail === 'string' && detail.length > 2, `body: ${JSON.stringify(body)}`);
        // noinspection JSObjectNullOrUndefined
        const detailArr = detail.slice(1, -1).split(', ');
        client.assert(detailArr.length > 0, `detail: ${JSON.stringify(detail)}`);
    });
%}

### Einen Vereine mit fehlerhaften Interessen mittels PATCH aktualisieren: 400 (Bad Request)
PATCH {{baseUrl}}/00000000-0000-0000-0000-000000000040
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

[
    { "op": "replace", "path": "/name", "value": "Neuername" },
    { "op": "replace", "path": "/email", "value": "new.email@test.de" },
    { "op": "add", "path": "/interessen", "value": "X" },
    { "op": "remove", "path": "/interessen", "value": "Y" }
]

> {%
    client.test('Einen Vereine mit fehlerhaften Interessen mittels PATCH aktualisieren: Bad Request (400)', () => {
        const status = response.status;
        client.assert(status === 400, `Falscher Statuscode: ${status}`);
    });

    client.test('Einen Vereine mit fehlerhaften Interessen mittels PATCH aktualisieren: body mit ProblemDetail', () => {
        const body = response.body;
        client.assert(typeof body === 'object', `body: ${JSON.stringify(body)}`);
         const detail = body.detail;
        client.assert(typeof detail === 'string', `body: ${JSON.stringify(body)}`);
        client.assert(detail === 'Mindestens eine ungueltige Patch-Operation', `detail: ${detail}`);
    });
%}
