' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml VereinWriteController

skinparam classAttributeIconSize 0

package org.springframework {
    package web.bind.annotation {
        interface "@PathVariable" as PathVariable

        interface "@RequestBody" as RequestBody
    }

    package http {
        class ResponseEntity<T>
        class ProblemDetail

    }
}

package jakarta.servlet.http {
    interface HttpServletRequest
}

package java.util {
    interface List<T>
    class UUID
}

package com.acme.verein {
    package service {
        class VereinWriteService << control >> << @Service >>
    }

    package rest #DDDDDD {
        package patch {
            class PatchOperation <<entity>>
        }

        class VereinDTO <<entity>>

        class VereinWriteController << boundary >> << @RestController >> << @RequestMapping >> {
            + @PostMapping create(@RequestBody VereinDTO: VereinDTO, request: HttpServletRequest): ResponseEntity<ProblemDetail>
            + @PutMapping update(@PathVariable id: UUID, @RequestBody VereinDTO: VereinDTO): ResponseEntity<ProblemDetail>
            + @PatchMapping patch(@PathVariable id: UUID, @RequestBody patchOps: List<PatchOperation>): ResponseEntity<ProblemDetail>
            + @DeleteMapping deleteById(@PathVariable id: UUID): ResponseEntity<Void>
        }

        VereinWriteController o-down-> "1" VereinWriteService : service
        VereinWriteController ..> VereinDTO
        VereinWriteController ..> ProblemDetail
        VereinWriteController ..> PatchOperation

        VereinWriteController .up.> ResponseEntity
        VereinWriteController .up.> HttpServletRequest

        VereinWriteController .up.> PathVariable
        VereinWriteController .up.> RequestBody

        VereinWriteController .up.> UUID
        VereinWriteController .up.> List

        PatchOperation .[hidden].> VereinWriteService
    }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
