' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml VereinGetController

skinparam classAttributeIconSize 0

package org.springframework {
    package web.bind.annotation {
        interface "@PathVariable" as PathVariable

        interface "@RequestParam" as RequestParam
    }
}

package java.util {
    interface Map<K,V>
    class UUID
    class Collection<T>
}

package com.acme.verein {
    package service {
        class VereinReadService << control >> << @Service >>
    }

    package rest #DDDDDD {
      class Verein <<entity>>

        class VereinGetController << boundary >> << @RestController >> << @RequestMapping >> {
            + @GetMapping findById(@PathVariable id: UUID): Verein
            + @GetMapping find(@RequestParam suchkriterien : final Map<String, String>): Verein
            + @Exceptionhandler onNotFound(final ex: NotFoundException): void
        }

        VereinGetController o-up-> "1" VereinReadService : service
        VereinGetController ..> Verein
        VereinGetController .down.> PathVariable
        VereinGetController .up.> RequestParam

        VereinGetController .up.> UUID
        VereinGetController .up.> Map
        VereinGetController .up.> Collection


    }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
